config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  get "/auth/:provider/callback", to: "sessions#create"
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, :path => '/sessions', :only => [:new, :create, :destroy]

  resources :workshops, :path => '/workshops', :only => [:index, :show] do
    resources :feedbacks
  end

  namespace :admin do
    resources :workshops do
      resources :feedbacks
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  belongs_to :workshop

  validates_length_of :body, minimum: 10
end

app/models/user.rb
class User < ApplicationRecord
  has_many :feedbacks, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.email = auth.info.email
      user.uid = auth.uid
      user.provider = auth.provider
      user.avatar_url = auth.info.image
      user.username = auth.info.name
      user.oauth_token = auth.credentials.token
      user.save!
    end
  end

  def admin?
    admin
  end
end

app/models/workshop.rb
class Workshop < ApplicationRecord
  has_many :feedbacks, dependent: :destroy

  validates_length_of :name, minimum: 5
  validates_length_of :description, minimum: 5
  validates_presence_of :url
end

app/controllers/admin/workshops_controller.rb
module Admin
  class WorkshopsController < ApplicationController
    before_action :authenticate_user!
    before_action :ensure_admin_user!

    def index
      @workshops = Workshop.all
    end

    def show
      @workshop = Workshop.find(params[:id])
    end

    def new
      @workshop = Workshop.new
    end

    def create
      workshop = Workshop.new(permitted_params)
      if workshop.valid?
        workshop.save
        flash[:notice] = 'Workshop created'
        redirect_to admin_workshop_path(workshop)
      else
        flash[:error] = "Create unsuccessful: #{workshop.errors.full_messages}"
        redirect_to new_admin_workshop_path(workshop)
      end
    end

    def edit
      @workshop = Workshop.find(params[:id])
    end

    def update
      workshop = Workshop.find(params[:id])
      workshop.update(permitted_params)
      if workshop.valid?
        workshop.save
        flash[:notice] = 'Workshop updated'
        redirect_to admin_workshop_path(workshop)
      else
        flash[:error] = "Update unsuccessful: #{workshop.errors.full_messages}"
        redirect_to edit_admin_workshop_path(workshop)
      end
    end

    def destroy
      workshop = Workshop.find(params[:id])
      workshop.destroy
      if workshop.persisted?
        flash[:error] = "Delete unsuccessful: #{workshop.errors.full_messages}"
        redirect_to admin_workshop_path(workshop)
      else
        flash[:notice] = 'Workshop deleted'
        redirect_to admin_workshops_path
      end
    end

    private

    def permitted_params
      params.require(:workshop).permit(:name, :url, :description, :image_url)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :authenticate_user!, :ensure_admin_user!

  def current_user
    User.find_by(id: session[:user_id])
  end

  def authenticate_user!
    unless logged_in?
       flash[:danger] = "Please log in."
       redirect_to root_path
    end
  end

  def ensure_admin_user!
    unless admin_user?
      flash[:danger] = "You do not have the required access"
      redirect_to root_path
    end
  end

  private

  def logged_in?
    current_user.present?
  end

  def admin_user?
    current_user.admin?
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :authenticate_user!

  def new
    @workshop = workshop
    @feedback = Feedback.new
  end

  def create
    feedback = Feedback.new(permitted_params.merge(workshop: workshop, user: current_user))
    if feedback.valid?
      feedback.save
      flash[:notice] = 'Feedback added'
      redirect_to workshop_path(workshop)
    else
      flash[:error] = "Feedback was not added: #{feedback.errors.full_messages}"
      redirect_to new_workshop_feedback_path(workshop)
    end
  end

  private

  def workshop
    Workshop.find(params[:workshop_id])
  end

  def permitted_params
    params.require(:feedback).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_omniauth(request.env["omniauth.auth"])

    if user.valid?
      session[:user_id] = user.id
      flash[:notice] = "You are now signed in"
      redirect_to root_path
    end
  end

  def destroy
    reset_session
    flash[:notice] = "You have signed out"
    redirect_to request.referer
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :authenticate_user!

  def index
    @workshops = Workshop.all
  end

  def show
    @workshop = Workshop.find(params[:id])
  end
end

app/helpers/admin/workshops_helper.rb
module Admin::WorkshopsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workshop_helper.rb
module WorkshopHelper
end

app/views/admin/workshops/edit.html.erb
<div class="demo-card-square mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title mdl-card--expand">
    <div class="mdl-card__supporting-text">
      <h2 class="mdl-card__title-text">Update a workshop</h2>
    </div>
  </div>
  <div class="mdl-card__supporting-text">
    <%= form_for [:admin, @workshop] do |f| %>
      <%= f.text_field :name, placeholder: 'Workshop name', class: 'mdl-textfield__input' %>
      <%= f.text_field :description, placeholder: 'a description', class: 'mdl-textfield__input' %>
      <%= f.url_field :image_url, placeholder: 'image url', class: 'mdl-textfield__input' %>
      <%= f.url_field :url, placeholder: 'The github repo', class: 'mdl-textfield__input' %>
      <%= f.submit 'Update Workshop', class: 'mdl-card__actions mdl-card--border mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
    <% end %>
  </div>
</div>

app/views/admin/workshops/index.html.erb
<div class="page-content workshop-create-button">
  <%= link_to('add workshop', new_admin_workshop_path, class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect") %>
</div>
<% @workshops.each do |workshop|  %>
  <div class="demo-card-square mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title mdl-card--expand">
      <h2 class="mdl-card__title-text"><%= link_to(workshop.name, admin_workshop_path(workshop)) %></h2>
    </div>
    <div class="mdl-card__supporting-text">
      <%= workshop.description %>
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <%= link_to('view on github', workshop.url, target: '_blank', class: "mdl-button mdl-js-button")  %>
    </div>
    <div class="mdl-card__menu">
      <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
        <i class="material-icons">share</i>
      </button>
    </div>
  </div>
<% end %>

app/views/admin/workshops/new.html.erb
<div class="demo-card-square mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title mdl-card--expand">
    <div class="mdl-card__supporting-text">
      <h2 class="mdl-card__title-text">Add a workshop</h2>
    </div>
  </div>
  <div class="mdl-card__supporting-text">
    <%= form_for [:admin, @workshop] do |f| %>
      <%= f.text_field :name, placeholder: 'Workshop name', class: 'mdl-textfield__input' %>
      <%= f.text_field :description, placeholder: 'a description', class: 'mdl-textfield__input' %>
      <%= f.url_field :image_url, placeholder: 'image url', class: 'mdl-textfield__input' %>
      <%= f.url_field :url, placeholder: 'The github repo', class: 'mdl-textfield__input' %>
      <%= f.submit 'Create Workshop', class: 'mdl-card__actions mdl-card--border mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
    <% end %>
  </div>
</div>

app/views/admin/workshops/show.html.erb
<div class="demo-card-square-main mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title mdl-card--expand">
    <div class="mdl-card__supporting-text">
      <h2 class="mdl-card__title-text"><%= @workshop.name %></h2>
    </div>
    <div class="mdl-card__supporting-text">
      <%= @workshop.description %>
    </div>
  </div>
  <div class="mdl-card__supporting-text">
    <%= link_to('Update', edit_admin_workshop_path(@workshop), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect") %>
    <%= link_to('Delete', admin_workshop_path(@workshop), method: :delete, class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect") %>
    <%= link_to('view on github', @workshop.url, target: '_blank', class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect")  %>
  </div>
</div>

<% @workshop.feedbacks.each do |feedback|  %>
  <div class="demo-card-square mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title mdl-card--expand">
      <div class="mdl-card__supporting-text feedback-body">
        <h2 class="mdl-card__title-text"><%= feedback.body %></h2>
      </div>
    </div>
    <div class="mdl-card__supporting-text">
      <%= image_tag feedback.user.avatar_url, class: "mdl-layout-icon feedback-avatar-image" %>
      <%= feedback.user.username %>
      <%= feedback.created_at.strftime("%m/%d/%Y at %H:%M") %>
    </div>
  </div>
<% end %>

app/views/feedbacks/new.html.erb
<div class="demo-card-square mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title mdl-card--expand">
    <div class="mdl-card__supporting-text">
      <h2 class="mdl-card__title-text">Give Feedback on</h2>
      <h3><%= @workshop.name %></h3>
    </div>
  </div>
  <div class="mdl-card__supporting-text">
    <%= form_for [@workshop, @feedback] do |f| %>
      <%= f.text_area :body, rows: '5', placeholder: 'What did you think?', class: 'mdl-textfield__input' %>
      <%= f.submit 'Add Feedback', class: 'mdl-card__actions mdl-card--border mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonsterCat</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">

      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <%= image_tag "cat-logo.jpg", class: "mdl-layout-icon nav-cat-logo" %>
          <span class="mdl-layout-title nav-title">MonsterCat</span>
          <div class="mdl-layout-spacer"></div>
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            <% if current_user %>
              <%= link_to('Sign out', signout_path, method: :delete, class: "mdl-navigation__link")%>
            <% end %>

            <% if current_user && current_user.admin? %>
              <%= link_to('Admin Workshops', admin_workshops_path, class: "mdl-navigation__link") %>
            <% end %>

            <%= link_to('Home', root_path, class: "mdl-navigation__link") %>
            <%= link_to('Workshops', workshops_path, class: "mdl-navigation__link") %>

          </nav>
        </div>
      </header>

      <main class="mdl-layout__content">
        <div class="page-content">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "flash #{name}" %>
          <% end -%>
          <%= yield %>
        </div>
      </main>

    </div>
  </body>
</html>

app/views/workshops/edit.html.erb
<div class="demo-card-square mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title mdl-card--expand">
    <div class="mdl-card__supporting-text">
      <h2 class="mdl-card__title-text">Update a workshop</h2>
    </div>
  </div>
  <div class="mdl-card__supporting-text">
    <%= form_for @workshop do |f| %>
      <%= f.text_field :name, placeholder: 'Workshop name', class: 'mdl-textfield__input' %>
      <%= f.text_field :description, placeholder: 'a description', class: 'mdl-textfield__input' %>
      <%= f.url_field :image_url, placeholder: 'image url', class: 'mdl-textfield__input' %>
      <%= f.url_field :url, placeholder: 'The github repo', class: 'mdl-textfield__input' %>
      <%= f.submit 'Update Workshop', class: 'mdl-card__actions mdl-card--border mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
    <% end %>
  </div>
</div>

app/views/workshops/index.html.erb
<div class="page-content workshop-create-button">
  <%= link_to('add workshop', new_workshop_path, class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect") %>
</div>
<% @workshops.each do |workshop|  %>
  <div class="demo-card-square mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title mdl-card--expand">
      <h2 class="mdl-card__title-text"><%= link_to(workshop.name, workshop_path(workshop)) %></h2>
    </div>
    <div class="mdl-card__supporting-text">
      <%= workshop.description %>
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <%= link_to('Add Feedback', new_workshop_feedback_path(workshop), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect") %>
      <%= link_to('view on github', workshop.url, target: '_blank', class: "mdl-button mdl-js-button")  %>
    </div>
    <div class="mdl-card__menu">
      <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
        <i class="material-icons">share</i>
      </button>
    </div>
  </div>
<% end %>

app/views/workshops/new.html.erb
<div class="demo-card-square mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title mdl-card--expand">
    <div class="mdl-card__supporting-text">
      <h2 class="mdl-card__title-text">Add a workshop</h2>
    </div>
  </div>
  <div class="mdl-card__supporting-text">
    <%= form_for @workshop do |f| %>
      <%= f.text_field :name, placeholder: 'Workshop name', class: 'mdl-textfield__input' %>
      <%= f.text_field :description, placeholder: 'a description', class: 'mdl-textfield__input' %>
      <%= f.url_field :image_url, placeholder: 'image url', class: 'mdl-textfield__input' %>
      <%= f.url_field :url, placeholder: 'The github repo', class: 'mdl-textfield__input' %>
      <%= f.submit 'Create Workshop', class: 'mdl-card__actions mdl-card--border mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
    <% end %>
  </div>
</div>

app/views/workshops/show.html.erb
<div class="demo-card-square-main mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title mdl-card--expand">
    <div class="mdl-card__supporting-text">
      <h2 class="mdl-card__title-text"><%= @workshop.name %></h2>
    </div>
    <div class="mdl-card__supporting-text">
      <%= @workshop.description %>
    </div>
  </div>
  <div class="mdl-card__supporting-text">
    <%= link_to('Update', edit_workshop_path(@workshop), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect") %>
    <%= link_to('Delete', workshop_path(@workshop), method: :delete, class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect") %>
    <%= link_to('Add Feedback', new_workshop_feedback_path(@workshop), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect") %>
    <%= link_to('view on github', @workshop.url, target: '_blank', class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect")  %>
  </div>
</div>

<% @workshop.feedbacks.each do |feedback|  %>
  <div class="demo-card-square mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title mdl-card--expand">
      <div class="mdl-card__supporting-text feedback-body">
        <h2 class="mdl-card__title-text"><%= feedback.body %></h2>
      </div>
    </div>
    <div class="mdl-card__supporting-text">
      <%= image_tag feedback.user.avatar_url, class: "mdl-layout-icon feedback-avatar-image" %>
      <%= feedback.user.username %>
      <%= feedback.created_at.strftime("%m/%d/%Y at %H:%M") %>
    </div>
  </div>
<% end %>